#!/bin/sh

## 28-08-17 RJ 0.00 Script to build Spider and MMTS on 'this' server and transport the binaries to devsys:/sm

cd `dirname $0`				# Make sure we're in the directory containing this script

DESTROOT=devsys:/sm				# Where we're going to put the results
NAMES="Spider, MMTS, wamper and libhydra.a"

case `uname` in
Linux)
	system=linux
	make=make
	;;
SCO_SV)
	system=sco
	make=gmake
	;;
Darwin)
	system=macos
	make=make
	;;
*)
	echo "I don't recognise this OS (`uname`)"
	exit 99
	;;
esac

echo Building $system versions of $NAMES for deposit in $DESTROOT...

for PASS in 1 2
do
	if [ $PASS = 1 ]; then
		FLAGS=
		type=release
	else
		FLAGS=-g
		type=debug
	fi

	TMP=/tmp/build.log
	rm -f $TMP
	SEND_LOG=
	if [ -f $TMP ]; then
		echo I cannot delete $TMP so there will be no log
	else
		SEND_LOG=YES
	fi

	echo Building $system $type
	$make spotless > $TMP 2>&1
	DEBUG=$FLAGS $make >> $TMP 2>&1

	egrep -i 'error|warning' $TMP

	chmod 755 bin/spider bin/mmts
	chmod 644 $TMP

	DEST=$DESTROOT/$system/$type

	scp -p bin/spider bin/mmts bin/wamper lib/libhydra.a $DEST >>$TMP 2>&1

	[ "$SEND_LOG" ] && scp -p $TMP $DEST 2>/dev/null

	echo $NAMES copied to $DEST
done
