#!/usr/bin/perl

my $src = $ARGV[0];

my $header = $src;
$header =~ s/\.c$/.h/ or die "Can't turn $src into a header name";
my $incvar = $header;
$incvar =~ s/.*\///;
$incvar = "__".uc $incvar;
$incvar =~ s/\./_/g;

open H, ">$header";
open S, $src or die;

print H "#ifndef $incvar\n";
print H "#define $incvar\n";
print H "\n";

my $commenting = 0;
my $haveCommented = 0;
for (<S>) {
	chomp;

	if (/^\/\/\s*START HEADER/) {
		$copy = 1;
		next;
	}

	if (/^\/\/\s*END HEADER/) {
		print H "\n";
		$copy = 0;
		next;
	}

	if ($copy) {
		print H "$_\n";
		next;
	}

	if (/^API/) {
		print H "\n" if $haveCommented;
		my $comment;
		$comment = $1 if (s/(\/\/.*)//);
		s/{.*//;
		s/\s+$//;
		s/^API\s*//;
		$_ .= ';';
		$_ .= $comment if $comment;
		print H "$_\n";
		$commenting = 1;
		$haveCommented=0;
		next;
	}

	if (/^\s*\/\//) {
		if ($commenting) {
			print H "$_\n";
			$haveCommented=1;
		}
	} else {
		$commenting = 0;
	}
}
close S;

print H "\n";
print H "#endif\n";
close H;

exit 0;
